// commands/test_lang.js

export const TRANSLATIONS = {
    'english': {
        code: 'en-US',
        start: "Starting User Interface Test Suite.",
        iso: "Setting up isometric view.",
        origin_hide: "Hiding the origin geometry.",
        origin_show: "Showing the origin geometry.",
        offset_plane: "Creating an offset work plane.",
        offset_axis: "Creating an offset work axis.",
        rot_plane: "Creating a rotated work plane.",
        rot_axis: "Creating a rotated work axis.",
        load_model: "Loading 3D model from URL.",
        focus_model: "Focusing on the new model.",
        move: "Moving the object.",
        rotate: "Rotating the object.",
        pat_rect: "Generating a rectangular pattern.",
        zoom_pat: "Zooming out to show full pattern.",
        pat_circ_z: "Generating a circular pattern around the global Z axis.",
        pat_circ_custom: "Generating a circular pattern around a custom work axis.",
        final_zoom: "Final zoom to show complex assembly.",
        bounds: "Toggling bounding box.",
        wireframe: "Switching to wireframe mode.",
        solid: "Reverting to solid mode.",
        section_on: "Enabling cross section view.",
        section_off: "Disabling cross section.",
        props: "Calculating physical properties.",
        final_iso: "Switching to isometric view.",
        complete: "Test suite completed successfully."
    },
    'hindi': {
        code: 'hi-IN',
        start: "User Interface Test Suite shuru kiya ja raha hai.",
        iso: "Isometric view set kiya ja raha hai.",
        origin_hide: "Origin geometry ko chupaya ja raha hai.",
        origin_show: "Origin geometry ko dikhaya ja raha hai.",
        offset_plane: "Ek offset work plane banaya ja raha hai.",
        offset_axis: "Ek offset work axis banaya ja raha hai.",
        rot_plane: "Ek rotated work plane banaya ja raha hai.",
        rot_axis: "Ek rotated work axis banaya ja raha hai.",
        load_model: "URL se 3D model load kiya ja raha hai.",
        focus_model: "Naye model par focus kiya ja raha hai.",
        move: "Object ko move kiya ja raha hai.",
        rotate: "Object ko rotate kiya ja raha hai.",
        pat_rect: "Rectangular pattern generate kiya ja raha hai.",
        zoom_pat: "Poora pattern dikhane ke liye zoom out kiya ja raha hai.",
        pat_circ_z: "Global Z axis ke charo taraf circular pattern banaya ja raha hai.",
        pat_circ_custom: "Custom work axis ke charo taraf circular pattern banaya ja raha hai.",
        final_zoom: "Complex assembly dikhane ke liye final zoom.",
        bounds: "Bounding box toggle kiya ja raha hai.",
        wireframe: "Wireframe mode mein switch kiya ja raha hai.",
        solid: "Solid mode mein wapis aa rahe hain.",
        section_on: "Cross section view enable kiya ja raha hai.",
        section_off: "Cross section disable kiya ja raha hai.",
        props: "Physical properties calculate ki ja rahi hain.",
        final_iso: "Isometric view mein wapis aa rahe hain.",
        complete: "Test suite safaltapoorvak poora hua."
    },
    'spanish': {
        code: 'es-ES',
        start: "Iniciando la suite de pruebas de interfaz de usuario.",
        iso: "Configurando vista isométrica.",
        origin_hide: "Ocultando la geometría de origen.",
        origin_show: "Mostrando la geometría de origen.",
        offset_plane: "Creando un plano de trabajo desplazado.",
        offset_axis: "Creando un eje de trabajo desplazado.",
        rot_plane: "Creando un plano de trabajo rotado.",
        rot_axis: "Creando un eje de trabajo rotado.",
        load_model: "Cargando modelo 3D desde URL.",
        focus_model: "Enfocando en el nuevo modelo.",
        move: "Moviendo el objeto.",
        rotate: "Rotando el objeto.",
        pat_rect: "Generando un patrón rectangular.",
        zoom_pat: "Alejando para mostrar el patrón completo.",
        pat_circ_z: "Generando un patrón circular alrededor del eje Z global.",
        pat_circ_custom: "Generando un patrón circular alrededor de un eje de trabajo personalizado.",
        final_zoom: "Zoom final para mostrar el ensamblaje complejo.",
        bounds: "Alternando cuadro delimitador.",
        wireframe: "Cambiando a modo estructura de alambre.",
        solid: "Volviendo a modo sólido.",
        section_on: "Habilitando vista de sección transversal.",
        section_off: "Deshabilitando sección transversal.",
        props: "Calculando propiedades físicas.",
        final_iso: "Cambiando a vista isométrica.",
        complete: "Suite de pruebas completada con éxito."
    },
    'chinese': {
        code: 'zh-CN',
        start: "开始用户界面测试套件。",
        iso: "设置等轴测视图。",
        origin_hide: "隐藏原点几何体。",
        origin_show: "显示原点几何体。",
        offset_plane: "创建偏移工作平面。",
        offset_axis: "创建偏移工作轴。",
        rot_plane: "创建旋转工作平面。",
        rot_axis: "创建旋转工作轴。",
        load_model: "正在从 URL 加载 3D 模型。",
        focus_model: "聚焦于新模型。",
        move: "移动物体。",
        rotate: "旋转物体。",
        pat_rect: "生成矩形阵列。",
        zoom_pat: "缩小以显示完整阵列。",
        pat_circ_z: "绕全局 Z 轴生成圆形阵列。",
        pat_circ_custom: "绕自定义工作轴生成圆形阵列。",
        final_zoom: "最终缩放以显示复杂组件。",
        bounds: "切换边界框显示。",
        wireframe: "切换到线框模式。",
        solid: "恢复实体模式。",
        section_on: "启用剖视图。",
        section_off: "禁用剖视图。",
        props: "计算物理属性。",
        final_iso: "切换回等轴测视图。",
        complete: "测试套件成功完成。"
    },
    'russian': {
        code: 'ru-RU',
        start: "Запуск набора тестов пользовательского интерфейса.",
        iso: "Установка изометрического вида.",
        origin_hide: "Скрытие геометрии начала координат.",
        origin_show: "Отображение геометрии начала координат.",
        offset_plane: "Создание смещенной рабочей плоскости.",
        offset_axis: "Создание смещенной рабочей оси.",
        rot_plane: "Создание повернутой рабочей плоскости.",
        rot_axis: "Создание повернутой рабочей оси.",
        load_model: "Загрузка 3D модели по URL.",
        focus_model: "Фокусировка на новой модели.",
        move: "Перемещение объекта.",
        rotate: "Вращение объекта.",
        pat_rect: "Создание прямоугольного массива.",
        zoom_pat: "Уменьшение масштаба для показа массива.",
        pat_circ_z: "Создание кругового массива вокруг оси Z.",
        pat_circ_custom: "Создание кругового массива вокруг своей оси.",
        final_zoom: "Финальное масштабирование.",
        bounds: "Переключение отображения границ.",
        wireframe: "Переключение в каркасный режим.",
        solid: "Возврат в режим твердого тела.",
        section_on: "Включение режима сечения.",
        section_off: "Отключение режима сечения.",
        props: "Расчет физических свойств.",
        final_iso: "Переключение в изометрический вид.",
        complete: "Набор тестов успешно выполнен."
    }
};