// commands/test_lang.js

export const TRANSLATIONS = {
    'english': {
        code: 'en-US',
        start: "Starting User Interface Test Suite.",
        iso: "Setting up isometric view.",
        origin_hide: "Hiding the origin geometry.",
        origin_show: "Showing the origin geometry.",
        offset_plane: "Creating an offset work plane.",
        offset_axis: "Creating an offset work axis.",
        rot_plane: "Creating a rotated work plane.",
        rot_axis: "Creating a rotated work axis.",
        param_add: "Creating a parametric cylinder.",
        sketch_start: "Entering Sketch Mode on XY Plane.",
        sketch_rect: "Drawing a 2D rectangle.",
        sketch_circ: "Drawing a 2D circle.",
        sketch_line: "Drawing a 2D line.",
        sketch_end: "Exiting Sketch Mode.",
        load_model: "Loading 3D model from URL.",
        focus_model: "Focusing on the new model.",
        move: "Moving the object.",
        rotate: "Rotating the object.",
        pat_rect: "Generating a rectangular pattern.",
        zoom_pat: "Zooming out to show full pattern.",
        pat_circ_z: "Generating a circular pattern around the global Z axis.",
        pat_circ_custom: "Generating a circular pattern around a custom work axis.",
        final_zoom: "Final zoom to show complex assembly.",
        bounds: "Toggling bounding box.",
        wireframe: "Switching to wireframe mode.",
        solid: "Reverting to solid mode.",
        section_on: "Enabling cross section view.",
        section_off: "Disabling cross section.",
        props: "Calculating physical properties.",
        measure_dist: "Activating distance measurement tool.",
        measure_angle: "Switching to angle measurement tool.",
        measure_off: "Disabling measurement tools.",
        col_enable: "Enabling collision detection system.",
        col_trigger: "Moving object to simulate collision.",
        col_clear: "Moving object to clear collision.",
        col_disable: "Collision test complete.",
        annot_add: "Adding a text annotation to the model.",
        annot_hide: "Hiding annotations.",
        annot_show: "Showing annotations again.",
        annot_clear: "Clearing all annotations.",
        tree_show: "Opening Feature Tree panel.",
        prop_add: "Adding a custom property.",
        prop_del: "Deleting the custom property.",
        obj_del: "Deleting the selected component.",
        tree_hide: "Closing Feature Tree panel.",
        save_session: "Saving the session state to a local file.",
        final_iso: "Switching to isometric view.",
        complete: "Test suite completed successfully."
    },
    'hindi': {
        code: 'hi-IN',
        start: "यूज़र इंटरफ़ेस टेस्ट सूट शुरू किया जा रहा है।",
        iso: "आइसोमेट्रिक दृश्य सेट किया जा रहा है।",
        origin_hide: "मूल ज्यामिति को छिपाया जा रहा है।",
        origin_show: "मूल ज्यामिति को दिखाया जा रहा है।",
        offset_plane: "एक ऑफसेट वर्क प्लेन बनाया जा रहा है।",
        offset_axis: "एक ऑफसेट वर्क एक्सिस बनाया जा रहा है।",
        rot_plane: "एक रोटेटेड वर्क प्लेन बनाया जा रहा है।",
        rot_axis: "एक रोटेटेड वर्क एक्सिस बनाया जा रहा है।",
        param_add: "एक पैरामीट्रिक सिलेंडर बनाया जा रहा है।",
        sketch_start: "XY प्लेन पर स्केच मोड शुरू किया जा रहा है।",
        sketch_rect: "एक 2D आयत (रेक्टेंगल) बनाया जा रहा है।",
        sketch_circ: "एक 2D वृत्त (सर्कल) बनाया जा रहा है।",
        sketch_line: "एक 2D रेखा (लाइन) बनाई जा रही है।",
        sketch_end: "स्केच मोड बंद किया जा रहा है।",
        load_model: "URL से 3D मॉडल लोड किया जा रहा है।",
        focus_model: "नए मॉडल पर फोकस किया जा रहा है।",
        move: "ऑब्जेक्ट को मूव किया जा रहा है।",
        rotate: "ऑब्जेक्ट को रोटेट किया जा रहा है।",
        pat_rect: "रेक्टेंगुलर पैटर्न जनरेट किया जा रहा है।",
        zoom_pat: "पूरा पैटर्न दिखाने के लिए ज़ूम आउट किया जा रहा है।",
        pat_circ_z: "ग्लोबल Z अक्ष के चारों ओर सर्कुलर पैटर्न बनाया जा रहा है।",
        pat_circ_custom: "कस्टम वर्क एक्सिस के चारों ओर सर्कुलर पैटर्न बनाया जा रहा है।",
        final_zoom: "जटिल असेंबली दिखाने के लिए अंतिम ज़ूम।",
        bounds: "बाउंडिंग बॉक्स टॉगल किया जा रहा है।",
        wireframe: "वायरफ्रेम मोड में स्विच किया जा रहा है।",
        solid: "सॉलिड मोड में वापस आ रहे हैं।",
        section_on: "क्रॉस सेक्शन दृश्य सक्षम किया जा रहा है।",
        section_off: "क्रॉस सेक्शन अक्षम किया जा रहा है।",
        props: "भौतिक गुणों की गणना की जा रही है।",
        measure_dist: "दूरी मापने का टूल सक्रिय किया जा रहा है।",
        measure_angle: "कोण मापने के टूल पर स्विच किया जा रहा है।",
        measure_off: "मापने वाले टूल बंद किए जा रहे हैं।",
        col_enable: "टकराव (कोलिजन) डिटेक्शन सिस्टम सक्षम किया जा रहा है।",
        col_trigger: "टकराव अनुकरण करने के लिए ऑब्जेक्ट को मूव किया जा रहा है।",
        col_clear: "टकराव हटाने के लिए ऑब्जेक्ट को मूव किया जा रहा है।",
        col_disable: "टकराव परीक्षण पूरा हुआ।",
        annot_add: "मॉडल पर टेक्स्ट एनोटेशन जोड़ा जा रहा है।",
        annot_hide: "एनोटेशन छिपाए जा रहे हैं।",
        annot_show: "एनोटेशन फिर से दिखाए जा रहे हैं।",
        annot_clear: "सभी एनोटेशन हटाए जा रहे हैं।",
        tree_show: "फीचर ट्री पैनल खोला जा रहा है।",
        prop_add: "एक कस्टम प्रॉपर्टी जोड़ी जा रही है।",
        prop_del: "कस्टम प्रॉपर्टी हटाई जा रही है।",
        obj_del: "चयनित घटक (कम्पोनेंट) हटाया जा रहा है।",
        tree_hide: "फीचर ट्री पैनल बंद किया जा रहा है।",
        save_session: "सत्र (सेशन) स्टेट को लोकल फ़ाइल में सहेज (सेव) जा रहा है।",
        final_iso: "आइसोमेट्रिक दृश्य में स्विच किया जा रहा है।",
        complete: "टेस्ट सूट सफलतापूर्वक पूरा हुआ।"
    },
    'spanish': {
        code: 'es-ES',
        start: "Iniciando la suite de pruebas de interfaz de usuario.",
        iso: "Configurando vista isométrica.",
        origin_hide: "Ocultando la geometría de origen.",
        origin_show: "Mostrando la geometría de origen.",
        offset_plane: "Creando un plano de trabajo desplazado.",
        offset_axis: "Creando un eje de trabajo desplazado.",
        rot_plane: "Creando un plano de trabajo rotado.",
        rot_axis: "Creando un eje de trabajo rotado.",
        param_add: "Creando un cilindro paramétrico.",
        sketch_start: "Entrando en modo de croquis en el plano XY.",
        sketch_rect: "Dibujando un rectángulo 2D.",
        sketch_circ: "Dibujando un círculo 2D.",
        sketch_line: "Dibujando una línea 2D.",
        sketch_end: "Saliendo del modo de croquis.",
        load_model: "Cargando modelo 3D desde URL.",
        focus_model: "Enfocando en el nuevo modelo.",
        move: "Moviendo el objeto.",
        rotate: "Rotando el objeto.",
        pat_rect: "Generando un patrón rectangular.",
        zoom_pat: "Alejando para mostrar el patrón completo.",
        pat_circ_z: "Generando un patrón circular alrededor del eje Z global.",
        pat_circ_custom: "Generando un patrón circular alrededor de un eje de trabajo personalizado.",
        final_zoom: "Zoom final para mostrar el ensamblaje complejo.",
        bounds: "Alternando cuadro delimitador.",
        wireframe: "Cambiando a modo estructura de alambre.",
        solid: "Volviendo a modo sólido.",
        section_on: "Habilitando vista de sección transversal.",
        section_off: "Deshabilitando sección transversal.",
        props: "Calculando propiedades físicas.",
        measure_dist: "Activando herramienta de medición de distancia.",
        measure_angle: "Cambiando a herramienta de medición de ángulo.",
        measure_off: "Desactivando herramientas de medición.",
        col_enable: "Habilitando sistema de detección de colisiones.",
        col_trigger: "Moviendo objeto para simular colisión.",
        col_clear: "Resolviendo colisión.",
        col_disable: "Prueba de colisión completada.",
        annot_add: "Añadiendo una anotación de texto al modelo.",
        annot_hide: "Ocultando anotaciones.",
        annot_show: "Mostrando anotaciones nuevamente.",
        annot_clear: "Borrando todas las anotaciones.",
        tree_show: "Abriendo el panel del Árbol de Características.",
        prop_add: "Añadiendo una propiedad personalizada.",
        prop_del: "Eliminando la propiedad personalizada.",
        obj_del: "Eliminando el componente seleccionado.",
        tree_hide: "Cerrando el panel del Árbol de Características.",
        save_session: "Guardando el estado de la sesión en un archivo local.",
        final_iso: "Cambiando a vista isométrica.",
        complete: "Suite de pruebas completada con éxito."
    },
    'chinese': {
        code: 'zh-CN',
        start: "开始用户界面测试套件。",
        iso: "设置等轴测视图。",
        origin_hide: "隐藏原点几何体。",
        origin_show: "显示原点几何体。",
        offset_plane: "创建偏移工作平面。",
        offset_axis: "创建偏移工作轴。",
        rot_plane: "创建旋转工作平面。",
        rot_axis: "创建旋转工作轴。",
        param_add: "创建参数化圆柱体。",
        sketch_start: "进入 XY 平面草图模式。",
        sketch_rect: "绘制 2D 矩形。",
        sketch_circ: "绘制 2D 圆形。",
        sketch_line: "绘制 2D 线条。",
        sketch_end: "退出草图模式。",
        load_model: "正在从 URL 加载 3D 模型。",
        focus_model: "聚焦于新模型。",
        move: "移动物体。",
        rotate: "旋转物体。",
        pat_rect: "生成矩形阵列。",
        zoom_pat: "缩小以显示完整阵列。",
        pat_circ_z: "绕全局 Z 轴生成圆形阵列。",
        pat_circ_custom: "绕自定义工作轴生成圆形阵列。",
        final_zoom: "最终缩放以显示复杂组件。",
        bounds: "切换边界框显示。",
        wireframe: "切换到线框模式。",
        solid: "恢复实体模式。",
        section_on: "启用剖视图。",
        section_off: "禁用剖视图。",
        props: "计算物理属性。",
        measure_dist: "激活距离测量工具。",
        measure_angle: "切换到角度测量工具。",
        measure_off: "禁用测量工具。",
        col_enable: "启用碰撞检测系统。",
        col_trigger: "移动物体以模拟碰撞。",
        col_clear: "移动物体以消除碰撞。",
        col_disable: "碰撞测试完成。",
        annot_add: "向模型添加文本注释。",
        annot_hide: "隐藏注释。",
        annot_show: "再次显示注释。",
        annot_clear: "清除所有注释。",
        tree_show: "打开功能树面板。",
        prop_add: "添加自定义属性。",
        prop_del: "删除自定义属性。",
        obj_del: "删除选定的组件。",
        tree_hide: "关闭功能树面板。",
        save_session: "将绘画会话状态保存到本地文件。",
        final_iso: "切换回等轴测视图。",
        complete: "测试套件成功完成。"
    },
    'russian': {
        code: 'ru-RU',
        start: "Запуск набора тестов пользовательского интерфейса.",
        iso: "Установка изометрического вида.",
        origin_hide: "Скрытие геометрии начала координат.",
        origin_show: "Отображение геометрии начала координат.",
        offset_plane: "Создание смещенной рабочей плоскости.",
        offset_axis: "Создание смещенной рабочей оси.",
        rot_plane: "Создание повернутой рабочей плоскости.",
        rot_axis: "Создание повернутой рабочей оси.",
        param_add: "Создание параметрического цилиндра.",
        sketch_start: "Вход в режим эскиза на плоскости XY.",
        sketch_rect: "Рисование 2D прямоугольника.",
        sketch_circ: "Рисование 2D окружности.",
        sketch_line: "Рисование 2D линии.",
        sketch_end: "Выход из режима эскиза.",
        load_model: "Загрузка 3D модели по URL.",
        focus_model: "Фокусировка на новой модели.",
        move: "Перемещение объекта.",
        rotate: "Вращение объекта.",
        pat_rect: "Создание прямоугольного массива.",
        zoom_pat: "Уменьшение масштаба для показа массива.",
        pat_circ_z: "Создание кругового массива вокруг оси Z.",
        pat_circ_custom: "Создание кругового массива вокруг своей оси.",
        final_zoom: "Финальное масштабирование.",
        bounds: "Переключение отображения границ.",
        wireframe: "Переключение в каркасный режим.",
        solid: "Возврат в режим твердого тела.",
        section_on: "Включение режима сечения.",
        section_off: "Отключение режима сечения.",
        props: "Расчет физических свойств.",
        measure_dist: "Активация инструмента измерения расстояния.",
        measure_angle: "Переключение на измерение угла.",
        measure_off: "Отключение инструментов измерения.",
        col_enable: "Включение системы обнаружения столкновений.",
        col_trigger: "Перемещение объекта для имитации столкновения.",
        col_clear: "Устранение столкновения.",
        col_disable: "Тест на столкновение завершен.",
        annot_add: "Добавление текстовой аннотации к модели.",
        annot_hide: "Скрытие аннотаций.",
        annot_show: "Отображение аннотаций.",
        annot_clear: "Очистка всех аннотаций.",
        tree_show: "Открытие дерева функций.",
        prop_add: "Добавление пользовательского свойства.",
        prop_del: "Удаление пользовательского свойства.",
        obj_del: "Удаление выбранного компонента.",
        tree_hide: "Закрытие дерева функций.",
        save_session: "Сохранение сеанса в локальный файл.",
        final_iso: "Переключение в изометрический вид.",
        complete: "Набор тестов успешно выполнен."
    }
};